### ISSUE TITLE
Value passed to parameter 'begin' has DataType float32 not in list of allowed values: int32, int64

### ISSUE THREAD

**Issue by naseeresmael** [tjvandal/srcnn-tensorflow#1]
hi @tjvandal 
 thanks for you work, when i begin the trining i found this error 

PS F:\SRCNN-tensorflow\example> python train.py
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    train()
  File "train.py", line 102, in train
    train_images, train_labels = inputs(True, FLAGS.batch_size, FLAGS.num_epochs)
  File "train.py", line 85, in inputs
    image, label = read_and_decode(filename_queue, is_training=train)
  File "train.py", line 69, in read_and_decode
    label = tf.slice(label, [FLAGS.padding, FLAGS.padding, 0], [label_y, label_x, -1])
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 561, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3125, in _slice
    name=name)
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 589, in apply_op
    param_name=input_name)
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 60, in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))
TypeError: Value passed to parameter 'begin' has DataType float32 not in list of allowed values: int32, int64

how can i fix that please.

**Comment by tjvandal** [comment]
@naseeresmael This is a python compatibility issue since I developed the code in python 2.7 and your showing an error on 3.5.  The issue is because FLAGS.padding is a float because in 3.5 int/int=float. 

Tomorrow I'll make edits so it'll run on 3.5, but for now change this line:
https://github.com/tjvandal/srcnn-tensorflow/blob/fa04bec9084cfc1e9bb34dbbec6aed17c7a6621b/example/train.py#L175
to:
`FLAGS.padding = int(abs(FLAGS.input_size - FLAGS.label_size) / 2)`

**Comment by naseeresmael** [comment]
great، much thanks for you @tjvandal.

**Comment by tjvandal** [comment]
@naseeresmael
